baseURL = "https://jailbreak-scratch.github.io"
languageCode = "en-us"
title = "Jailbreak Scratch!"
theme = "uBlogger"

[params]
  version = "2.0.X"
  [params.page]
	[params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false

  [params.comment]
    enable = true
	  
	  [params.comment.utterances]
        enable = true
        # owner/repo
        repo = "Jailbreak-Scratch/site-dev"
        issueTerm = "pathname"
        label = "comments"
        lightTheme = "github-light"
        darkTheme = "github-dark"