baseURL = "https://jailbreak-scratch.github.io"
languageCode = "en-us"
title = "Jailbreak Scratch!"
theme = "uBlogger"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "latest"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Latest Maps"
    url = "/pages/latest/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2

[params]
  version = "2.0.X"
  [params.page]
	[params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false

  [params.comment]
    enable = true
	  
	  [params.comment.utterances]
        enable = true
        # owner/repo
        repo = "Jailbreak-Scratch/site-dev"
        issueTerm = "pathname"
        label = "comments"
        lightTheme = "github-light"
        darkTheme = "github-dark"
	
	[params.search]
		enable = true
		type = "lunr"
		contentLength = 4000
		placeholder = "Search!"
		maxResultLength = 10
		snippetLength = 30
		absoluteURL = false
	[params.verification]
		google = "qo6WnRYfvYXiLpeYmO018wxIK_ht5aDC-15wKcIe7NQ"